# Generated by Django 5.1.6 on 2025-02-11 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('tc', models.BooleanField()),
                ('user_role', models.CharField(max_length=40)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=50)),
                ('pickup_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WMS_User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('image_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='PickupOrder',
            fields=[
                ('pickup_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=50)),
                ('pickup_date', models.DateTimeField()),
                ('weight', models.CharField(max_length=20)),
                ('waste_type', models.CharField(max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
