# Generated by Django 5.1.6 on 2025-02-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('company', 'Company')], max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
