# Generated by Django 5.1.6 on 2025-02-10 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('image_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PickupOrder',
            fields=[
                ('pickup_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=50)),
                ('pickup_date', models.DateTimeField()),
                ('weight', models.CharField(max_length=20)),
                ('waste_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=50)),
                ('pickup_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WMS_User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=40)),
                ('email', models.EmailField(default='example@example.com', max_length=100, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_photo', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store'),
        ),
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wms_user'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wms_user'),
        ),
    ]
