# Generated by Django 5.1.6 on 2025-02-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0002_rename_user_wuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WUser',
            new_name='User',
        ),
    ]
