# Generated by Django 5.1.6 on 2025-03-03 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('waste_item_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('accuracy_score', models.FloatField()),
                ('identified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('waste_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastecategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.DeleteModel(
            name='WMS_User',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
