# Generated by Django 5.1.6 on 2025-03-04 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wastecategory_wasteitem_remove_image_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='pickup_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='request_status',
            new_name='reward_status',
        ),
        migrations.RenameField(
            model_name='wasteitem',
            old_name='waste_item_image_id',
            new_name='waste_item_id',
        ),
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wastecategory',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wastecategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('pickup_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=20)),
                ('waste_type', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('pickup_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pickuprequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reedemption',
            fields=[
                ('reedemption_id', models.AutoField(primary_key=True, serialize=False)),
                ('reedemption_date', models.DateField()),
                ('points_reedemed', models.FloatField()),
                ('reward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reward')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PickupOrder',
        ),
    ]
