# Generated by Django 5.1.6 on 2025-03-04 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_pickup_date_reward_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
