# Generated by Django 5.1.6 on 2025-03-04 04:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_image_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
