# Generated by Django 5.1.6 on 2025-03-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_image_image_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_type',
        ),
    ]
