# Generated by Django 5.1.6 on 2025-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_image_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='accuracy_score',
            field=models.FloatField(null=True),
        ),
    ]
