# Generated by Django 5.1.6 on 2025-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_wasteitem_accuracy_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecategory',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
