# Generated by Django 5.1.6 on 2025-03-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_wastecategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteitem',
            old_name='waste_category',
            new_name='category_id',
        ),
    ]
