# Generated by Django 5.1.6 on 2025-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_created_date_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='weight_metric',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='weight',
            field=models.FloatField(),
        ),
    ]
