# Generated by Django 5.1.6 on 2025-04-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pickuprequest_weight_metric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_file_url',
            new_name='image_file',
        ),
    ]
