# Generated by Django 5.1.6 on 2025-04-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_image_file_image_image_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_file_url',
            new_name='image_file',
        ),
    ]
