# Generated by Django 5.1.6 on 2025-04-08 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_image_file_url_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='request_date',
        ),
        migrations.AddField(
            model_name='reward',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
