# Generated by Django 5.1.6 on 2025-04-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_user_id_expopushtoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expopushtoken',
            old_name='user',
            new_name='user_id',
        ),
    ]
