# Generated by Django 5.1.6 on 2025-04-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_user_expopushtoken_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expopushtoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
